// Utility to upload test data to Firebase
// Use this file to upload new tests generated by LLM

import { uploadTest } from './firebaseData';
import { Question, TestInfo } from '@/types';

// ===============================
// TEMPLATE FOR LLM-GENERATED DATA
// ===============================

/*
STRUCTURE FOR LLM TO GENERATE:

export const testData = {
  testInfo: {
    id: '', // Will be auto-generated
    name: 'JEE Main Mock Test 2',
    testType: 'Full Test' as const,
    scheduledDate: new Date('2024-12-18T10:00:00'),
    duration: 180, // in minutes
    totalQuestions: 75,
    subjects: ['Mathematics', 'Physics', 'Chemistry'] as ('Mathematics' | 'Physics' | 'Chemistry')[],
    maxMarks: 300,
    status: 'Upcoming' as const,
    attempts: 0
  },
  questions: [
    {
      id: '', // Will be auto-generated
      subject: 'Mathematics' as const,
      chapter: 'Quadratic Equations',
      topic: 'Sum and Product of Roots',
      type: 'MCQ' as const,
      questionNumber: 1,
      imagePath: '/questions/test-2/math/mcq/1.png',
      solutionPath: '/questions/test-2/math/solutions/1.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'A',
      marks: {
        correct: 4,
        incorrect: -1
      },
      difficulty: 'Medium' as const,
      idealTime: 120 // in seconds
    },
    // ... more questions
  ]
};
*/

// ===============================
// SAMPLE TEST DATA (for reference)
// ===============================

const sampleTestData = {
  testInfo: {
    id: '', // Will be auto-generated
    name: 'JEE Main Sample Test',
    type: 'JEE' as const,
    testType: 'Full Test' as const,
    scheduledDate: new Date('2024-12-25T10:00:00'),
    duration: 180,
    totalQuestions: 6, // Small sample
    subjects: ['Mathematics', 'Physics', 'Chemistry'] as ('Mathematics' | 'Physics' | 'Chemistry')[],
    maxMarks: 24,
    status: 'Upcoming' as const,
    attempts: 0,
    description: 'Sample JEE test for validation and smoke testing.',
    createdAt: new Date()
  },
  questions: [
    // Math questions
    {
      id: '',
      subject: 'Mathematics' as const,
      chapter: 'Algebra',
      topic: 'Quadratic Equations',
      type: 'MCQ' as const,
      questionNumber: 1,
      imagePath: '/questions/sample-test/math/mcq/1.png',
      solutionPath: '/questions/sample-test/math/solutions/1.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'A',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Easy' as const,
      idealTime: 90
    },
    {
      id: '',
      subject: 'Mathematics' as const,
      chapter: 'Calculus',
      topic: 'Derivatives',
      type: 'Integer' as const,
      questionNumber: 2,
      imagePath: '/questions/sample-test/math/integer/1.png',
      solutionPath: '/questions/sample-test/math/solutions/2.png',
      correctAnswer: '5',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Medium' as const,
      idealTime: 120
    },
    // Physics questions
    {
      id: '',
      subject: 'Physics' as const,
      chapter: 'Mechanics',
      topic: 'Kinematics',
      type: 'MCQ' as const,
      questionNumber: 3,
      imagePath: '/questions/sample-test/physics/mcq/1.png',
      solutionPath: '/questions/sample-test/physics/solutions/1.png',
      options: ['10 m/s', '15 m/s', '20 m/s', '25 m/s'],
      correctAnswer: 'B',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Medium' as const,
      idealTime: 120
    },
    {
      id: '',
      subject: 'Physics' as const,
      chapter: 'Thermodynamics',
      topic: 'Heat Transfer',
      type: 'Integer' as const,
      questionNumber: 4,
      imagePath: '/questions/sample-test/physics/integer/1.png',
      solutionPath: '/questions/sample-test/physics/solutions/2.png',
      correctAnswer: '3',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Hard' as const,
      idealTime: 150
    },
    // Chemistry questions
    {
      id: '',
      subject: 'Chemistry' as const,
      chapter: 'Organic Chemistry',
      topic: 'Hydrocarbons',
      type: 'MCQ' as const,
      questionNumber: 5,
      imagePath: '/questions/sample-test/chemistry/mcq/1.png',
      solutionPath: '/questions/sample-test/chemistry/solutions/1.png',
      options: ['C2H4', 'C2H6', 'C3H6', 'C3H8'],
      correctAnswer: 'C',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Easy' as const,
      idealTime: 100
    },
    {
      id: '',
      subject: 'Chemistry' as const,
      chapter: 'Physical Chemistry',
      topic: 'Atomic Structure',
      type: 'Integer' as const,
      questionNumber: 6,
      imagePath: '/questions/sample-test/chemistry/integer/1.png',
      solutionPath: '/questions/sample-test/chemistry/solutions/2.png',
      correctAnswer: '8',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Medium' as const,
      idealTime: 110
    }
  ]
};

// ===============================
// UPLOAD FUNCTIONS
// ===============================

// Function to upload a single test
export async function uploadSingleTest(testData: { testInfo: TestInfo, questions: Question[] }) {
  try {
    console.log('Uploading test:', testData.testInfo.name);
    const testId = await uploadTest(testData.testInfo, testData.questions);
    console.log('✅ Test uploaded successfully with ID:', testId);
    return testId;
  } catch (error) {
    console.error('❌ Failed to upload test:', error);
    throw error;
  }
}

// Function to upload the sample test (for testing purposes)
export async function uploadSampleTest() {
  return await uploadSingleTest(sampleTestData);
}

// ===============================
// INSTRUCTIONS FOR USAGE
// ===============================

/*
HOW TO USE THIS SYSTEM:

1. **Generate Test Data with LLM:**
   - Copy the structure template above
   - Give it to your LLM with specific test requirements
   - LLM will fill in all the details

2. **Create New Test File:**
   - Create a file like `src/data/jee-test-3.ts`
   - Paste the LLM-generated data
   - Export it as `testData`

3. **Upload to Firebase:**
   - Import the test data
   - Call `uploadSingleTest(testData)`
   - The test will appear in your JEE Tests section

4. **Image Organization:**
   - Store images in: `public/questions/test-name/subject/type/number.png`
   - Example: `public/questions/jee-mock-3/math/mcq/1.png`

5. **Example Upload Script:**
   ```typescript
   import { testData } from '../data/jee-test-3';
   import { uploadSingleTest } from '../lib/uploadTestData';
   
   // Upload the test
   uploadSingleTest(testData);
   ```
*/

export default uploadSingleTest;
