// Simple script to upload a new test
import { uploadSingleTest } from '../lib/uploadTestData';
import { Question, TestInfo } from '@/types';

// ===============================
// FILLED-IN TEST DATA
// ===============================

export const testData = {
  testInfo: {
    id: '', // Will be auto-generated
    name: 'Sample JEE Test ',
    testType: 'Full Test' as const,
    scheduledDate: new Date('2024-12-25T10:00:00'),
    duration: 180, // in minutes
    totalQuestions: 75,
    subjects: ['Mathematics', 'Physics', 'Chemistry'] as ('Mathematics' | 'Physics' | 'Chemistry')[],
    maxMarks: 300,
    status: 'Upcoming' as const,
    attempts: 0,
    type: 'JEE' as const, // For categorizing the test (e.g., 'JEE' or 'UGEE'),
    description: 'A full mock test based on the latest JEE pattern.',
    createdAt: new Date(), // Automatically sets the creation date to now
  },
  questions: [
    // ===============================
    // Mathematics Questions (25)
    // ===============================
    // Chapter: Matrices & Determinants (8 Questions)
    {
      id: '',
      subject: 'Mathematics' as const,
      chapter: 'Matrices & Determinants',
      topic: 'Properties of Determinants',
      type: 'MCQ' as const,
      questionNumber: 1,
      imagePath: '/questions/sample-test/mathematics/AD1WT7-M61.png',
      solutionPath: '/questions/sample-test/mathematics/AD1WT7-M61.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'A',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Medium' as const,
      idealTime: 120
    },
    {
      id: '',
      subject: 'Mathematics' as const,
      chapter: 'Matrices & Determinants',
      topic: 'Inverse of a Matrix',
      type: 'MCQ' as const,
      questionNumber: 2,
      imagePath: '/questions/sample-test/mathematics/AD1WT7-M62.png',
      solutionPath: '/questions/sample-test/mathematics/AD1WT7-M62.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'C',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Medium' as const,
      idealTime: 130
    },
    {
      id: '',
      subject: 'Mathematics' as const,
      chapter: 'Matrices & Determinants',
      topic: 'Adjoint of a Matrix',
      type: 'MCQ' as const,
      questionNumber: 3,
      imagePath: '/questions/sample-test/mathematics/AD1WT7-M63.png',
      solutionPath: '/questions/sample-test/mathematics/AD1WT7-M63.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'B',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Easy' as const,
      idealTime: 110
    },
    {
      id: '',
      subject: 'Mathematics' as const,
      chapter: 'Matrices & Determinants',
      topic: 'System of Linear Equations',
      type: 'MCQ' as const,
      questionNumber: 4,
      imagePath: '/questions/sample-test/mathematics/AD1WT7-M64.png',
      solutionPath: '/questions/sample-test/mathematics/AD1WT7-M64.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'D',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Hard' as const,
      idealTime: 150
    },
    {
      id: '',
      subject: 'Mathematics' as const,
      chapter: 'Matrices & Determinants',
      topic: 'Matrix Multiplication',
      type: 'MCQ' as const,
      questionNumber: 5,
      imagePath: '/questions/sample-test/mathematics/AD1WT7-M65.png',
      solutionPath: '/questions/sample-test/mathematics/AD1WT7-M65.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'A',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Medium' as const,
      idealTime: 120
    },
    {
      id: '',
      subject: 'Mathematics' as const,
      chapter: 'Matrices & Determinants',
      topic: 'Properties of Matrices',
      type: 'MCQ' as const,
      questionNumber: 6,
      imagePath: '/questions/sample-test/mathematics/AD1WT7-M66.png',
      solutionPath: '/questions/sample-test/mathematics/AD1WT7-M66.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'C',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Medium' as const,
      idealTime: 130
    },
    {
      id: '',
      subject: 'Mathematics' as const,
      chapter: 'Matrices & Determinants',
      topic: 'Cramer\'s Rule',
      type: 'MCQ' as const,
      questionNumber: 7,
      imagePath: '/questions/sample-test/mathematics/AD1WT7-M67.png',
      solutionPath: '/questions/sample-test/mathematics/AD1WT7-M67.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'B',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Medium' as const,
      idealTime: 140
    },
    {
      id: '',
      subject: 'Mathematics' as const,
      chapter: 'Matrices & Determinants',
      topic: 'System of Linear Equations',
      type: 'MCQ' as const,
      questionNumber: 8,
      imagePath: '/questions/sample-test/mathematics/AD1WT7-M68.png',
      solutionPath: '/questions/sample-test/mathematics/AD1WT7-M68.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'B',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Hard' as const,
      idealTime: 150
    },
    // Chapter: Calculus (9 Questions)
    {
      id: '',
      subject: 'Mathematics' as const,
      chapter: 'Calculus',
      topic: 'Limits and Continuity',
      type: 'MCQ' as const,
      questionNumber: 9,
      imagePath: '/questions/sample-test/mathematics/AD1WT7-M69.png',
      solutionPath: '/questions/sample-test/mathematics/AD1WT7-M69.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'D',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Easy' as const,
      idealTime: 100
    },
    {
      id: '',
      subject: 'Mathematics' as const,
      chapter: 'Calculus',
      topic: 'Application of Derivatives',
      type: 'MCQ' as const,
      questionNumber: 10,
      imagePath: '/questions/sample-test/mathematics/AD1WT7-M70.png',
      solutionPath: '/questions/sample-test/mathematics/AD1WT7-M70.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'A',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Medium' as const,
      idealTime: 120
    },
    {
      id: '',
      subject: 'Mathematics' as const,
      chapter: 'Calculus',
      topic: 'Indefinite Integration',
      type: 'MCQ' as const,
      questionNumber: 11,
      imagePath: '/questions/sample-test/mathematics/AD1WT7-M71.png',
      solutionPath: '/questions/sample-test/mathematics/AD1WT7-M71.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'C',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Medium' as const,
      idealTime: 130
    },
    {
      id: '',
      subject: 'Mathematics' as const,
      chapter: 'Calculus',
      topic: 'Differential Equations',
      type: 'MCQ' as const,
      questionNumber: 12,
      imagePath: '/questions/sample-test/mathematics/AD1WT7-M72.png',
      solutionPath: '/questions/sample-test/mathematics/AD1WT7-M72.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'B',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Hard' as const,
      idealTime: 150
    },
    {
      id: '',
      subject: 'Mathematics' as const,
      chapter: 'Calculus',
      topic: 'Area Under Curves',
      type: 'MCQ' as const,
      questionNumber: 13,
      imagePath: '/questions/sample-test/mathematics/AD1WT7-M73.png',
      solutionPath: '/questions/sample-test/mathematics/AD1WT7-M73.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'A',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Medium' as const,
      idealTime: 140
    },
    {
      id: '',
      subject: 'Mathematics' as const,
      chapter: 'Calculus',
      topic: 'Maxima and Minima',
      type: 'MCQ' as const,
      questionNumber: 14,
      imagePath: '/questions/sample-test/mathematics/AD1WT7-M74.png',
      solutionPath: '/questions/sample-test/mathematics/AD1WT7-M74.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'D',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Medium' as const,
      idealTime: 130
    },
    {
      id: '',
      subject: 'Mathematics' as const,
      chapter: 'Calculus',
      topic: 'Differentiability',
      type: 'MCQ' as const,
      questionNumber: 15,
      imagePath: '/questions/sample-test/mathematics/AD1WT7-M75.png',
      solutionPath: '/questions/sample-test/mathematics/AD1WT7-M75.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'C',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Easy' as const,
      idealTime: 110
    },
    {
      id: '',
      subject: 'Mathematics' as const,
      chapter: 'Calculus',
      topic: 'Methods of Integration',
      type: 'MCQ' as const,
      questionNumber: 16,
      imagePath: '/questions/sample-test/mathematics/AD1WT7-M76.png',
      solutionPath: '/questions/sample-test/mathematics/AD1WT7-M76.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'B',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Hard' as const,
      idealTime: 160
    },
    {
      id: '',
      subject: 'Mathematics' as const,
      chapter: 'Calculus',
      topic: 'Definite Integration',
      type: 'Integer' as const,
      questionNumber: 17,
      imagePath: '/questions/sample-test/mathematics/AD1WT7-M77.png',
      solutionPath: '/questions/sample-test/mathematics/AD1WT7-M77.png',
      correctAnswer: '5',
      marks: { correct: 4, incorrect: 0 },
      difficulty: 'Hard' as const,
      idealTime: 160
    },
    // Chapter: Coordinate Geometry (8 Questions)
    {
      id: '',
      subject: 'Mathematics' as const,
      chapter: 'Coordinate Geometry',
      topic: 'Straight Lines',
      type: 'MCQ' as const,
      questionNumber: 18,
      imagePath: '/questions/sample-test/mathematics/AD1WT7-M78.png',
      solutionPath: '/questions/sample-test/mathematics/AD1WT7-M78.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'C',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Easy' as const,
      idealTime: 90
    },
    {
      id: '',
      subject: 'Mathematics' as const,
      chapter: 'Coordinate Geometry',
      topic: 'Circles',
      type: 'MCQ' as const,
      questionNumber: 19,
      imagePath: '/questions/sample-test/mathematics/AD1WT7-M79.png',
      solutionPath: '/questions/sample-test/mathematics/AD1WT7-M79.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'A',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Medium' as const,
      idealTime: 120
    },
    {
      id: '',
      subject: 'Mathematics' as const,
      chapter: 'Coordinate Geometry',
      topic: 'Parabola',
      type: 'MCQ' as const,
      questionNumber: 20,
      imagePath: '/questions/sample-test/mathematics/AD1WT7-M80.png',
      solutionPath: '/questions/sample-test/mathematics/AD1WT7-M80.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'D',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Medium' as const,
      idealTime: 130
    },
    {
      id: '',
      subject: 'Mathematics' as const,
      chapter: 'Coordinate Geometry',
      topic: 'Ellipse and Hyperbola',
      type: 'Integer' as const,
      questionNumber: 21,
      imagePath: '/questions/sample-test/mathematics/AD1WT7-M81.png',
      solutionPath: '/questions/sample-test/mathematics/AD1WT7-M81.png',
      correctAnswer: '8',
      marks: { correct: 4, incorrect: 0 },
      difficulty: 'Hard' as const,
      idealTime: 150
    },
    {
      id: '',
      subject: 'Mathematics' as const,
      chapter: 'Coordinate Geometry',
      topic: 'Distance Formula',
      type: 'Integer' as const,
      questionNumber: 22,
      imagePath: '/questions/sample-test/mathematics/AD1WT7-M82.png',
      solutionPath: '/questions/sample-test/mathematics/AD1WT7-M82.png',
      correctAnswer: '10',
      marks: { correct: 4, incorrect: 0 },
      difficulty: 'Easy' as const,
      idealTime: 100
    },
    {
      id: '',
      subject: 'Mathematics' as const,
      chapter: 'Coordinate Geometry',
      topic: 'Section Formula',
      type: 'Integer' as const,
      questionNumber: 23,
      imagePath: '/questions/sample-test/mathematics/AD1WT7-M83.png',
      solutionPath: '/questions/sample-test/mathematics/AD1WT7-M83.png',
      correctAnswer: '3',
      marks: { correct: 4, incorrect: 0 },
      difficulty: 'Medium' as const,
      idealTime: 120
    },
    {
      id: '',
      subject: 'Mathematics' as const,
      chapter: 'Coordinate Geometry',
      topic: 'Area of Triangle',
      type: 'Integer' as const,
      questionNumber: 24,
      imagePath: '/questions/sample-test/mathematics/AD1WT7-M84.png',
      solutionPath: '/questions/sample-test/mathematics/AD1WT7-M84.png',
      correctAnswer: '15',
      marks: { correct: 4, incorrect: 0 },
      difficulty: 'Medium' as const,
      idealTime: 130
    },
    {
      id: '',
      subject: 'Mathematics' as const,
      chapter: 'Coordinate Geometry',
      topic: 'Locus Problems',
      type: 'Integer' as const,
      questionNumber: 25,
      imagePath: '/questions/sample-test/mathematics/AD1WT7-M85.png',
      solutionPath: '/questions/sample-test/mathematics/AD1WT7-M85.png',
      correctAnswer: '12',
      marks: { correct: 4, incorrect: 0 },
      difficulty: 'Hard' as const,
      idealTime: 150
    },

    // ===============================
    // Physics Questions (25)
    // ===============================
    // Chapter: Mechanics (8 Questions)
    {
      id: '',
      subject: 'Physics' as const,
      chapter: 'Mechanics',
      topic: 'Kinematics',
      type: 'MCQ' as const,
      questionNumber: 26,
      imagePath: '/questions/sample-test/physics/PJA25-1.png',
      solutionPath: '/questions/sample-test/physics/PJA25-1.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'B',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Easy' as const,
      idealTime: 100
    },
    {
      id: '',
      subject: 'Physics' as const,
      chapter: 'Mechanics',
      topic: 'Laws of Motion',
      type: 'MCQ' as const,
      questionNumber: 27,
      imagePath: '/questions/sample-test/physics/PJA25-2.png',
      solutionPath: '/questions/sample-test/physics/PJA25-2.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'A',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Medium' as const,
      idealTime: 120
    },
    {
      id: '',
      subject: 'Physics' as const,
      chapter: 'Mechanics',
      topic: 'Work, Energy, and Power',
      type: 'MCQ' as const,
      questionNumber: 28,
      imagePath: '/questions/sample-test/physics/PJA25-3.png',
      solutionPath: '/questions/sample-test/physics/PJA25-3.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'C',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Medium' as const,
      idealTime: 130
    },
    {
      id: '',
      subject: 'Physics' as const,
      chapter: 'Mechanics',
      topic: 'System of Particles and Rotational Motion',
      type: 'MCQ' as const,
      questionNumber: 29,
      imagePath: '/questions/sample-test/physics/PJA25-4.png',
      solutionPath: '/questions/sample-test/physics/PJA25-4.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'D',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Hard' as const,
      idealTime: 150
    },
    {
      id: '',
      subject: 'Physics' as const,
      chapter: 'Mechanics',
      topic: 'Gravitation',
      type: 'MCQ' as const,
      questionNumber: 30,
      imagePath: '/questions/sample-test/physics/PJA25-5.png',
      solutionPath: '/questions/sample-test/physics/PJA25-5.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'B',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Medium' as const,
      idealTime: 120
    },
    {
      id: '',
      subject: 'Physics' as const,
      chapter: 'Mechanics',
      topic: 'Properties of Solids and Liquids',
      type: 'MCQ' as const,
      questionNumber: 31,
      imagePath: '/questions/sample-test/physics/PJA25-6.png',
      solutionPath: '/questions/sample-test/physics/PJA25-6.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'A',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Medium' as const,
      idealTime: 130
    },
    {
      id: '',
      subject: 'Physics' as const,
      chapter: 'Mechanics',
      topic: 'Oscillations and Waves',
      type: 'MCQ' as const,
      questionNumber: 32,
      imagePath: '/questions/sample-test/physics/PJA25-7.png',
      solutionPath: '/questions/sample-test/physics/PJA25-7.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'C',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Hard' as const,
      idealTime: 140
    },
    {
      id: '',
      subject: 'Physics' as const,
      chapter: 'Mechanics',
      topic: 'Rotational Motion',
      type: 'MCQ' as const,
      questionNumber: 33,
      imagePath: '/questions/sample-test/physics/PJA25-8.png',
      solutionPath: '/questions/sample-test/physics/PJA25-8.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'D',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Hard' as const,
      idealTime: 140
    },
    // Chapter: Electrodynamics (9 Questions)
    {
      id: '',
      subject: 'Physics' as const,
      chapter: 'Electrodynamics',
      topic: 'Electric Charges and Fields',
      type: 'MCQ' as const,
      questionNumber: 34,
      imagePath: '/questions/sample-test/physics/PJA25-9.png',
      solutionPath: '/questions/sample-test/physics/PJA25-9.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'A',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Medium' as const,
      idealTime: 120
    },
    {
      id: '',
      subject: 'Physics' as const,
      chapter: 'Electrodynamics',
      topic: 'Electrostatic Potential and Capacitance',
      type: 'MCQ' as const,
      questionNumber: 35,
      imagePath: '/questions/sample-test/physics/PJA25-10.png',
      solutionPath: '/questions/sample-test/physics/PJA25-10.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'B',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Medium' as const,
      idealTime: 130
    },
    {
      id: '',
      subject: 'Physics' as const,
      chapter: 'Electrodynamics',
      topic: 'Current Electricity',
      type: 'MCQ' as const,
      questionNumber: 36,
      imagePath: '/questions/sample-test/physics/PJA25-11.png',
      solutionPath: '/questions/sample-test/physics/PJA25-11.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'C',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Hard' as const,
      idealTime: 150
    },
    {
      id: '',
      subject: 'Physics' as const,
      chapter: 'Electrodynamics',
      topic: 'Moving Charges and Magnetism',
      type: 'MCQ' as const,
      questionNumber: 37,
      imagePath: '/questions/sample-test/physics/PJA25-12.png',
      solutionPath: '/questions/sample-test/physics/PJA25-12.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'D',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Hard' as const,
      idealTime: 160
    },
    {
      id: '',
      subject: 'Physics' as const,
      chapter: 'Electrodynamics',
      topic: 'Magnetism and Matter',
      type: 'MCQ' as const,
      questionNumber: 38,
      imagePath: '/questions/sample-test/physics/PJA25-13.png',
      solutionPath: '/questions/sample-test/physics/PJA25-13.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'A',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Easy' as const,
      idealTime: 100
    },
    {
      id: '',
      subject: 'Physics' as const,
      chapter: 'Electrodynamics',
      topic: 'Electromagnetic Induction',
      type: 'MCQ' as const,
      questionNumber: 39,
      imagePath: '/questions/sample-test/physics/PJA25-14.png',
      solutionPath: '/questions/sample-test/physics/PJA25-14.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'B',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Medium' as const,
      idealTime: 140
    },
    {
      id: '',
      subject: 'Physics' as const,
      chapter: 'Electrodynamics',
      topic: 'Alternating Current',
      type: 'MCQ' as const,
      questionNumber: 40,
      imagePath: '/questions/sample-test/physics/PJA25-15.png',
      solutionPath: '/questions/sample-test/physics/PJA25-15.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'C',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Medium' as const,
      idealTime: 130
    },
    {
      id: '',
      subject: 'Physics' as const,
      chapter: 'Electrodynamics',
      topic: 'Electromagnetic Waves',
      type: 'MCQ' as const,
      questionNumber: 41,
      imagePath: '/questions/sample-test/physics/PJA25-16.png',
      solutionPath: '/questions/sample-test/physics/PJA25-16.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'D',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Easy' as const,
      idealTime: 110
    },
    {
      id: '',
      subject: 'Physics' as const,
      chapter: 'Electrodynamics',
      topic: 'Electromagnetic Induction',
      type: 'Integer' as const,
      questionNumber: 42,
      imagePath: '/questions/sample-test/physics/PJA25-17.png',
      solutionPath: '/questions/sample-test/physics/PJA25-17.png',
      correctAnswer: '2',
      marks: { correct: 4, incorrect: 0 },
      difficulty: 'Hard' as const,
      idealTime: 150
    },
    // Chapter: Modern Physics (8 Questions)
    {
      id: '',
      subject: 'Physics' as const,
      chapter: 'Modern Physics',
      topic: 'Dual Nature of Radiation and Matter',
      type: 'MCQ' as const,
      questionNumber: 43,
      imagePath: '/questions/sample-test/physics/PJA25-18.png',
      solutionPath: '/questions/sample-test/physics/PJA25-18.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'C',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Medium' as const,
      idealTime: 110
    },
    {
      id: '',
      subject: 'Physics' as const,
      chapter: 'Modern Physics',
      topic: 'Atoms',
      type: 'MCQ' as const,
      questionNumber: 44,
      imagePath: '/questions/sample-test/physics/PJA25-19.png',
      solutionPath: '/questions/sample-test/physics/PJA25-19.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'A',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Easy' as const,
      idealTime: 100
    },
    {
      id: '',
      subject: 'Physics' as const,
      chapter: 'Modern Physics',
      topic: 'Nuclei',
      type: 'MCQ' as const,
      questionNumber: 45,
      imagePath: '/questions/sample-test/physics/PJA25-20.png',
      solutionPath: '/questions/sample-test/physics/PJA25-20.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'B',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Medium' as const,
      idealTime: 120
    },
    {
      id: '',
      subject: 'Physics' as const,
      chapter: 'Modern Physics',
      topic: 'Semiconductor Electronics',
      type: 'Integer' as const,
      questionNumber: 46,
      imagePath: '/questions/sample-test/physics/PJA25-21.png',
      solutionPath: '/questions/sample-test/physics/PJA25-21.png',
      correctAnswer: '3',
      marks: { correct: 4, incorrect: 0 },
      difficulty: 'Hard' as const,
      idealTime: 140
    },
    {
      id: '',
      subject: 'Physics' as const,
      chapter: 'Modern Physics',
      topic: 'Photoelectric Effect',
      type: 'Integer' as const,
      questionNumber: 47,
      imagePath: '/questions/sample-test/physics/PJA25-22.png',
      solutionPath: '/questions/sample-test/physics/PJA25-22.png',
      correctAnswer: '6',
      marks: { correct: 4, incorrect: 0 },
      difficulty: 'Medium' as const,
      idealTime: 130
    },
    {
      id: '',
      subject: 'Physics' as const,
      chapter: 'Modern Physics',
      topic: 'Radioactivity',
      type: 'Integer' as const,
      questionNumber: 48,
      imagePath: '/questions/sample-test/physics/PJA25-23.png',
      solutionPath: '/questions/sample-test/physics/PJA25-23.png',
      correctAnswer: '4',
      marks: { correct: 4, incorrect: 0 },
      difficulty: 'Hard' as const,
      idealTime: 150
    },
    {
      id: '',
      subject: 'Physics' as const,
      chapter: 'Modern Physics',
      topic: 'X-rays',
      type: 'Integer' as const,
      questionNumber: 49,
      imagePath: '/questions/sample-test/physics/PJA25-24.png',
      solutionPath: '/questions/sample-test/physics/PJA25-24.png',
      correctAnswer: '9',
      marks: { correct: 4, incorrect: 0 },
      difficulty: 'Medium' as const,
      idealTime: 120
    },
    {
      id: '',
      subject: 'Physics' as const,
      chapter: 'Modern Physics',
      topic: 'Logic Gates',
      type: 'Integer' as const,
      questionNumber: 50,
      imagePath: '/questions/sample-test/physics/PJA25-25.png',
      solutionPath: '/questions/sample-test/physics/PJA25-25.png',
      correctAnswer: '1',
      marks: { correct: 4, incorrect: 0 },
      difficulty: 'Medium' as const,
      idealTime: 120
    },

    // ===============================
    // Chemistry Questions (25)
    // ===============================
    // Chapter: Atomic Structure (8 Questions)
    {
      id: '',
      subject: 'Chemistry' as const,
      chapter: 'Atomic Structure',
      topic: 'Bohr Model',
      type: 'MCQ' as const,
      questionNumber: 51,
      imagePath: '/questions/sample-test/chemistry/AD1WT7-C31.png',
      solutionPath: '/questions/sample-test/chemistry/AD1WT7-C31.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'D',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Easy' as const,
      idealTime: 90
    },
    {
      id: '',
      subject: 'Chemistry' as const,
      chapter: 'Atomic Structure',
      topic: 'Quantum Numbers',
      type: 'MCQ' as const,
      questionNumber: 52,
      imagePath: '/questions/sample-test/chemistry/AD1WT7-C32.png',
      solutionPath: '/questions/sample-test/chemistry/AD1WT7-C32.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'A',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Medium' as const,
      idealTime: 110
    },
    {
      id: '',
      subject: 'Chemistry' as const,
      chapter: 'Atomic Structure',
      topic: 'Electronic Configuration',
      type: 'MCQ' as const,
      questionNumber: 53,
      imagePath: '/questions/sample-test/chemistry/AD1WT7-C33.png',
      solutionPath: '/questions/sample-test/chemistry/AD1WT7-C33.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'C',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Easy' as const,
      idealTime: 100
    },
    {
      id: '',
      subject: 'Chemistry' as const,
      chapter: 'Atomic Structure',
      topic: 'de Broglie Wavelength',
      type: 'MCQ' as const,
      questionNumber: 54,
      imagePath: '/questions/sample-test/chemistry/AD1WT7-C34.png',
      solutionPath: '/questions/sample-test/chemistry/AD1WT7-C34.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'B',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Medium' as const,
      idealTime: 120
    },
    {
      id: '',
      subject: 'Chemistry' as const,
      chapter: 'Atomic Structure',
      topic: 'Heisenberg Uncertainty Principle',
      type: 'MCQ' as const,
      questionNumber: 55,
      imagePath: '/questions/sample-test/chemistry/AD1WT7-C35.png',
      solutionPath: '/questions/sample-test/chemistry/AD1WT7-C35.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'D',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Hard' as const,
      idealTime: 140
    },
    {
      id: '',
      subject: 'Chemistry' as const,
      chapter: 'Atomic Structure',
      topic: 'Photoelectric Effect',
      type: 'MCQ' as const,
      questionNumber: 56,
      imagePath: '/questions/sample-test/chemistry/AD1WT7-C36.png',
      solutionPath: '/questions/sample-test/chemistry/AD1WT7-C36.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'A',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Medium' as const,
      idealTime: 130
    },
    {
      id: '',
      subject: 'Chemistry' as const,
      chapter: 'Atomic Structure',
      topic: 'Spectral Lines',
      type: 'MCQ' as const,
      questionNumber: 57,
      imagePath: '/questions/sample-test/chemistry/AD1WT7-C37.png',
      solutionPath: '/questions/sample-test/chemistry/AD1WT7-C37.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'C',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Hard' as const,
      idealTime: 150
    },
    {
      id: '',
      subject: 'Chemistry' as const,
      chapter: 'Atomic Structure',
      topic: 'Orbitals and Shapes',
      type: 'MCQ' as const,
      questionNumber: 58,
      imagePath: '/questions/sample-test/chemistry/AD1WT7-C38.png',
      solutionPath: '/questions/sample-test/chemistry/AD1WT7-C38.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'B',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Easy' as const,
      idealTime: 100
    },
    // Chapter: Chemical Bonding and Molecular Structure (9 Questions)
    {
      id: '',
      subject: 'Chemistry' as const,
      chapter: 'Chemical Bonding and Molecular Structure',
      topic: 'VSEPR Theory',
      type: 'MCQ' as const,
      questionNumber: 59,
      imagePath: '/questions/sample-test/chemistry/AD1WT7-C39.png',
      solutionPath: '/questions/sample-test/chemistry/AD1WT7-C39.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'A',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Easy' as const,
      idealTime: 80
    },
    {
      id: '',
      subject: 'Chemistry' as const,
      chapter: 'Chemical Bonding and Molecular Structure',
      topic: 'Hybridization',
      type: 'MCQ' as const,
      questionNumber: 60,
      imagePath: '/questions/sample-test/chemistry/AD1WT7-C40.png',
      solutionPath: '/questions/sample-test/chemistry/AD1WT7-C40.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'C',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Medium' as const,
      idealTime: 120
    },
    {
      id: '',
      subject: 'Chemistry' as const,
      chapter: 'Chemical Bonding and Molecular Structure',
      topic: 'Molecular Orbital Theory',
      type: 'MCQ' as const,
      questionNumber: 61,
      imagePath: '/questions/sample-test/chemistry/AD1WT7-C41.png',
      solutionPath: '/questions/sample-test/chemistry/AD1WT7-C41.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'B',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Hard' as const,
      idealTime: 150
    },
    {
      id: '',
      subject: 'Chemistry' as const,
      chapter: 'Chemical Bonding and Molecular Structure',
      topic: 'Dipole Moment',
      type: 'MCQ' as const,
      questionNumber: 62,
      imagePath: '/questions/sample-test/chemistry/AD1WT7-C42.png',
      solutionPath: '/questions/sample-test/chemistry/AD1WT7-C42.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'D',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Medium' as const,
      idealTime: 130
    },
    {
      id: '',
      subject: 'Chemistry' as const,
      chapter: 'Chemical Bonding and Molecular Structure',
      topic: 'Hydrogen Bonding',
      type: 'MCQ' as const,
      questionNumber: 63,
      imagePath: '/questions/sample-test/chemistry/AD1WT7-C43.png',
      solutionPath: '/questions/sample-test/chemistry/AD1WT7-C43.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'A',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Easy' as const,
      idealTime: 100
    },
    {
      id: '',
      subject: 'Chemistry' as const,
      chapter: 'Chemical Bonding and Molecular Structure',
      topic: 'Ionic Bond',
      type: 'MCQ' as const,
      questionNumber: 64,
      imagePath: '/questions/sample-test/chemistry/AD1WT7-C44.png',
      solutionPath: '/questions/sample-test/chemistry/AD1WT7-C44.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'C',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Easy' as const,
      idealTime: 90
    },
    {
      id: '',
      subject: 'Chemistry' as const,
      chapter: 'Chemical Bonding and Molecular Structure',
      topic: 'Covalent Bond',
      type: 'MCQ' as const,
      questionNumber: 65,
      imagePath: '/questions/sample-test/chemistry/AD1WT7-C45.png',
      solutionPath: '/questions/sample-test/chemistry/AD1WT7-C45.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'B',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Medium' as const,
      idealTime: 110
    },
    {
      id: '',
      subject: 'Chemistry' as const,
      chapter: 'Chemical Bonding and Molecular Structure',
      topic: 'Fajans Rules',
      type: 'MCQ' as const,
      questionNumber: 66,
      imagePath: '/questions/sample-test/chemistry/AD1WT7-C46.png',
      solutionPath: '/questions/sample-test/chemistry/AD1WT7-C46.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'D',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Hard' as const,
      idealTime: 140
    },
    {
      id: '',
      subject: 'Chemistry' as const,
      chapter: 'Chemical Bonding and Molecular Structure',
      topic: 'Bond Order',
      type: 'Integer' as const,
      questionNumber: 67,
      imagePath: '/questions/sample-test/chemistry/AD1WT7-C47.png',
      solutionPath: '/questions/sample-test/chemistry/AD1WT7-C47.png',
      correctAnswer: '4',
      marks: { correct: 4, incorrect: 0 },
      difficulty: 'Medium' as const,
      idealTime: 130
    },
    // Chapter: Organic Chemistry: Some Basic Principles and Techniques (8 Questions)
    {
      id: '',
      subject: 'Chemistry' as const,
      chapter: 'Organic Chemistry: Some Basic Principles and Techniques',
      topic: 'IUPAC Nomenclature',
      type: 'MCQ' as const,
      questionNumber: 68,
      imagePath: '/questions/sample-test/chemistry/AD1WT7-C48.png',
      solutionPath: '/questions/sample-test/chemistry/AD1WT7-C48.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'C',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Medium' as const,
      idealTime: 110
    },
    {
      id: '',
      subject: 'Chemistry' as const,
      chapter: 'Organic Chemistry: Some Basic Principles and Techniques',
      topic: 'Isomerism',
      type: 'MCQ' as const,
      questionNumber: 69,
      imagePath: '/questions/sample-test/chemistry/AD1WT7-C49.png',
      solutionPath: '/questions/sample-test/chemistry/AD1WT7-C49.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'A',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Hard' as const,
      idealTime: 150
    },
    {
      id: '',
      subject: 'Chemistry' as const,
      chapter: 'Organic Chemistry: Some Basic Principles and Techniques',
      topic: 'Inductive Effect',
      type: 'MCQ' as const,
      questionNumber: 70,
      imagePath: '/questions/sample-test/chemistry/AD1WT7-C50.png',
      solutionPath: '/questions/sample-test/chemistry/AD1WT7-C50.png',
      options: ['A', 'B', 'C', 'D'],
      correctAnswer: 'B',
      marks: { correct: 4, incorrect: -1 },
      difficulty: 'Easy' as const,
      idealTime: 100
    },
    {
      id: '',
      subject: 'Chemistry' as const,
      chapter: 'Organic Chemistry: Some Basic Principles and Techniques',
      topic: 'Resonance',
      type: 'Integer' as const,
      questionNumber: 71,
      imagePath: '/questions/sample-test/chemistry/AD1WT7-C51.png',
      solutionPath: '/questions/sample-test/chemistry/AD1WT7-C51.png',
      correctAnswer: '5',
      marks: { correct: 4, incorrect: 0 },
      difficulty: 'Medium' as const,
      idealTime: 130
    },
    {
      id: '',
      subject: 'Chemistry' as const,
      chapter: 'Organic Chemistry: Some Basic Principles and Techniques',
      topic: 'Hyperconjugation',
      type: 'Integer' as const,
      questionNumber: 72,
      imagePath: '/questions/sample-test/chemistry/AD1WT7-C52.png',
      solutionPath: '/questions/sample-test/chemistry/AD1WT7-C52.png',
      correctAnswer: '6',
      marks: { correct: 4, incorrect: 0 },
      difficulty: 'Medium' as const,
      idealTime: 120
    },
    {
      id: '',
      subject: 'Chemistry' as const,
      chapter: 'Organic Chemistry: Some Basic Principles and Techniques',
      topic: 'Carbocation Stability',
      type: 'Integer' as const,
      questionNumber: 73,
      imagePath: '/questions/sample-test/chemistry/AD1WT7-C53.png',
      solutionPath: '/questions/sample-test/chemistry/AD1WT7-C53.png',
      correctAnswer: '1',
      marks: { correct: 4, incorrect: 0 },
      difficulty: 'Hard' as const,
      idealTime: 140
    },
    {
      id: '',
      subject: 'Chemistry' as const,
      chapter: 'Organic Chemistry: Some Basic Principles and Techniques',
      topic: 'Carbanion Stability',
      type: 'Integer' as const,
      questionNumber: 74,
      imagePath: '/questions/sample-test/chemistry/AD1WT7-C54.png',
      solutionPath: '/questions/sample-test/chemistry/AD1WT7-C54.png',
      correctAnswer: '3',
      marks: { correct: 4, incorrect: 0 },
      difficulty: 'Medium' as const,
      idealTime: 130
    },
    {
      id: '',
      subject: 'Chemistry' as const,
      chapter: 'Organic Chemistry: Some Basic Principles and Techniques',
      topic: 'Purification Methods',
      type: 'Integer' as const,
      questionNumber: 75,
      imagePath: '/questions/sample-test/chemistry/AD1WT7-C55.png',
      solutionPath: '/questions/sample-test/chemistry/AD1WT7-C55.png',
      correctAnswer: '2',
      marks: { correct: 4, incorrect: 0 },
      difficulty: 'Medium' as const,
      idealTime: 120
    }
  ]
};


async function uploadMyTest() {
  try {
    console.log('🚀 Uploading test to Firebase...');
    console.log('📝 Test name:', testData.testInfo.name);
    console.log('📊 Total questions:', testData.questions.length);
    
    const testId = await uploadSingleTest(testData);
    
    console.log('✅ SUCCESS! Test uploaded with ID:', testId);
    console.log('🎯 Go check your Firebase console');
    console.log('🌐 Refresh your website to see the new test');
    
  } catch (error) {
    console.error('❌ FAILED to upload test:', error);
  }
}

// Run the upload
uploadMyTest();
